Document: guvcview
Title: Debian guvcview Manual
Author: Paulo Assis
Abstract: This manual describes what guvcview is
 and how it can be used to
 manage online manuals on Debian systems.
Section: Audio&Video

Format: debiandoc-sgml
Files: /usr/share/doc/guvcview/guvcview.sgml.gz

Format: postscript
Files: /usr/share/doc/guvcview/guvcview.ps.gz

Format: text
Files: /usr/share/doc/guvcview/guvcview.text.gz

Format: HTML
Index: /usr/share/doc/guvcview/html/index.html
Files: /usr/share/doc/guvcview/html/*.html

  
