.TH GUVCVIEW "2" "Jun 2009"
.SH NAME
guvcview \- GTK+ base UVC Viewer 
.SH SYNOPSIS
.B guvcview
.SH DESCRIPTION
\f Guvcview is a simple GTK+ interface for capturing and viewing video from
devices supported by the Linux UVC driver.
It fully supports video4linux2 so it should work with any driver that supports
this API, including the gspca driver. \f

.SH USAGE
.TP
guvcview [options...] 

.SH OPTION
  \-?, \-\-help                   Print help options
  \-\-help\-all                   Print all help options
  \-\-help\-gtk                   Print GTK+ options
  \-\-version                    Print version number

Aplication options:
  \-v, \-\-verbose                Prints a lot of debug information
  \-d, \-\-device=VIDEO_DEVICE    Video Device [default: /dev/video0]
  \-o, \-\-control_only           Don't stream video (image controls only)
  \-g, \-\-config=FILENAME        Configuration File
  \-w, \-\-hwd_acel=[1 | 0]       Hardware accelaration (enable(1) | disable(0))
  \-f, \-\-format=FORMAT          Video input format:
                       mjpg | jpeg | yuyv | uyvy | yyuv | yu12 |
                       yv12 | gbrg | grbg | bggr | rggb
  \-s, \-\-size=WIDTHxHEIGHT      Resolution, default: 640x480
  \-i, \-\-image=FILENAME         Image File
  \-c, \-\-cap_time=TIME          Time elapsed between image captures
  \-m, \-\-npics=NUMPIC           Number of images to capture
  \-n, \-\-avi=FILENAME           Video File (capture from start)
  \-t, \-\-avi_time=TIME          Video duration (in seconds)
  \-p, \-\-show_fps=[1 | 0]       Print FPS on video Window (enable(1) | disable(0))
  \-l, \-\-profile=FILENAME       Load profile


.SH AUTHOR
This manual page was written by Paulo Assis <pj.assis@gmail.com>,
for the Debian GNU/Linux system (but may be used by others).
