.TH GUVCVIEW "1" "May 2024"
.SH NAME
guvcview \- GTK+ base UVC Viewer 
.SH SYNOPSIS
.B guvcview
.SH DESCRIPTION
\fBGuvcview\fR is an application for capturing and viewing video from
devices supported by the linux kernel video4linux2 interface.

.SH USAGE
.TP
guvcview [options...] 

.SH OPTIONS
.TP
.B -h,--help
Print help
.TP
.B -v,--version
Print version
.TP
.B -w,--verbosity=LEVEL
Set Verbosity level (def: 0)
.TP
.B -d,--device=AUDIO_DEVICE
Set device name (def: /dev/video0)
.TP
.B -c,--capture=METHOD
Set capture method [read | mmap (def)]
.TP
.B -b,--disable_libv4l2
disable calls to libv4l2
.TP
.B -x,--resolution=WIDTHxHEIGHT
Request resolution (e.g 640x480)
.TP
.B -f,--format=FOURCC
Request format (e.g MJPG)
.TP
.B -F,--fps=FPS_NUM[/FPS_DENOM] 
Request fps (e.g. 25 ; 7/3; ...)
.TP
.B -r,--render=RENDER_API
Select render API (e.g none; sdl; sfml)
.TP
.B -m,--render_window=RENDER_WINDOW_FLAGS	
Set render window flags (e.g none; full; max; WIDTHxHEIGHT)
.TP
.B -a,--audio=AUDIO_API
Select audio API (e.g none; port; pulse)
.TP
.B -k,--audio_device=audio_device
Select audio device index for selected api (0..N)
.TP
.B -g,--gui=GUI_API
Select GUI API (e.g none; gtk3; qt6)
.TP
.B -o,--audio_codec=codecAudio
Audio codec [pcm mp2 mp3 aac ac3 vorb]
.TP
.B -u,--video_codec=codec
Video codec [raw mjpg mpeg flv1 wmv1 mpg2 mp43
             dx50 h264 vp80 theo]
.TP
.B -p,--profile=filename
Load control profile
.TP
.B -j,--video=filename
filename for captured video)
.TP
.B -i,--image=filename
filename for captured image)
.TP
.B -y,--video_timer=TIME_IN_SEC
Time (double) in sec. for video capture)
.TP
.B -t,--photo_timer=TIME_IN_SEC
Time (double) in sec. between captured photos)
.TP
.B -n,--photo_total=total
Total number of captured photos)
.TP
.B -e,--exit_on_term
Exit app after video or image capture ends
.TP
.B -z,--control_panel
Start in control panel mode

.SH AUTHOR
This manual page was written by Paulo Assis <pj.assis@gmail.com>,
for the Debian GNU/Linux system (but may be used by others).
